# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &default
  adapter: postgresql
  database: welcome_development
  pool: 5
  host: localhost

test:
  <<: *default
  database: welcome_test
